version: '3.8'

services:
  db:
    image: mysql:8.0
    ports:
      - "6603:3306"
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  php:
    build: .
    volumes:
      - ./php:/var/www/html
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:80"
